POST http://localhost:8000/login/
Content-Type: application/json

{
    "username": "ali",
    "password": "a1234",
    "email": "ali@example.com"
}


###


POST http://localhost:8000/register/
Content-Type: application/json

{
    "username": "ali",
    "password": "a1234"
}